/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package pl.apurtak.cinema

import pl.apurtak.cinema.moviescatalog.MoviesCatalogConfiguration
import pl.apurtak.cinema.moviescatalog.model.Movie
import java.util.*

class App {
    val moviesCatalog = MoviesCatalogConfiguration.inMemoryCatalog()
}

fun main() {
    val app  = App()
    val shrek = Movie(
        id = UUID.randomUUID(),
        name = "Shrek",
        durationMinutes = 90,
        threeDimensionalGlassesNeeded = false
    )
    val theGodfather = Movie(
        id = UUID.randomUUID(),
        name = "The Godfather",
        durationMinutes = 120,
        threeDimensionalGlassesNeeded = false
    )
    app.moviesCatalog.add(shrek)
    app.moviesCatalog.add(theGodfather)

    println("Available movies: ${app.moviesCatalog.listMovies()}")

}
