/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package pl.apurtak.cinema

import pl.apurtak.cinema.jdbc.JdbcCinemaScheduleEventsStore
import pl.apurtak.cinema.moviescatalog.MoviesCatalogConfiguration
import pl.apurtak.cinema.moviescatalog.model.Movie
import pl.apurtak.cinema.schedule.service.CinemaScheduleAppService
import pl.apurtak.cinema.schedule.service.EnrichedRoomEvent
import pl.apurtak.cinema.schedule.service.ScheduleCommandValidator
import pl.apurtak.cinema.schedule.service.ScheduleShowCommand
import pl.apurtak.cinema.validators.PremierStartTimeValidator
import pl.apurtak.cinema.validators.ShowStartTimeValidator
import java.time.LocalDate
import java.time.LocalTime
import java.util.*

class App {
    private val appConfig = AppConfig(
        cleaningSlotDurationMinutes = 15,
        allowedShowStartTimeRange = LocalTime.of(8,0)..LocalTime.of(22, 0),
        allowedPremierStartTimeRange = LocalTime.of(17, 0)..LocalTime.of(21,0))
    val moviesCatalog = MoviesCatalogConfiguration.inMemoryCatalog()
    private val scheduleCommandValidators = listOf(
        ShowStartTimeValidator(appConfig),
        PremierStartTimeValidator(appConfig)
    )
    val cinemaScheduleAppService = CinemaScheduleAppService(
        JdbcCinemaScheduleEventsStore(),
        moviesCatalog,
        scheduleCommandValidators,
        appConfig
    )
}

fun main() {
    val app  = App()
    val shrek = Movie(
        id = UUID.randomUUID(),
        name = "Shrek",
        durationMinutes = 90,
        threeDimensionalGlassesNeeded = false
    )
    val theGodfather = Movie(
        id = UUID.randomUUID(),
        name = "The Godfather",
        durationMinutes = 120,
        threeDimensionalGlassesNeeded = false
    )
    app.moviesCatalog.add(shrek)
    app.moviesCatalog.add(theGodfather)

    println("Available movies: ${app.moviesCatalog.listMovies()}")

    app.cinemaScheduleAppService.scheduleShow(
        ScheduleShowCommand(
            roomId = "1",
            movieName = "Shrek",
            date = LocalDate.of(2023, 4, 27),
            startTime = LocalTime.of(17, 0),
            isPremier = true
        )
    )
    app.cinemaScheduleAppService.scheduleShow(
        ScheduleShowCommand(
            roomId = "1",
            movieName = "Shrek",
            date = LocalDate.of(2023, 4, 27),
            startTime = LocalTime.of(19, 0),
            isPremier = false
        )
    )

    app.cinemaScheduleAppService.scheduleShow(
        ScheduleShowCommand(
            roomId = "2",
            movieName = "The Godfather",
            date = LocalDate.of(2023, 4, 27),
            startTime = LocalTime.of(18, 0),
            isPremier = false
        )
    )

    val room1Schedule = app.cinemaScheduleAppService.getRoomSchedule("1", LocalDate.of(2023, 4, 27))
    println("Room 1 schedule:\n${room1Schedule.prettyPrint()} \n")

    val room2Schedule = app.cinemaScheduleAppService.getRoomSchedule("2", LocalDate.of(2023, 4, 27))
    println("Room 2 schedule:\n${room2Schedule.prettyPrint()} \n")

}

private fun List<EnrichedRoomEvent>.prettyPrint() =
    this.joinToString("\n")